version: '2'
services:
  fcrepo4:
    image: mikelynch/fcrepo4-docker:tag-webac
    ports:
      - 8080:8080
      - 8090:8090

  fcrepo4py:
    build: .
    volumes:
      - .:/code
    command: /bin/bash /code/run-fcrepo4-tests.sh
